### ISSUE TITLE
Bug - Solver API Unit Test Failure

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#100]
### Problem
The solver unit tests fails after implementing #93, the solver returns failure, but previously it didn't. A quick look suggests the unit test should not fail.

**Expected behavior:**  
The test ``./tests/test/test_api/test_solve.py`` passes unit tests.

**Actual behavior:**  
```
======================================================================
FAIL: test_init (test.test_api.test_solve.TestSolve)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\USER\dev\mayaMatchMoveSolver_maya2018Deploy_windows64\tests\test\test_api\test_solve.py", line 117, in test_init
    self.checkSolveResults(results)
  File "C:\Users\USER\dev\mayaMatchMoveSolver_maya2018Deploy_windows64\tests\test\test_api\test_solve.py", line 34, in checkSolveResults
    self.assertTrue(success)
AssertionError: False is not true
```
### Steps to Reproduce

After building normally, run the unit tests.
For example:
1. Run in Command Line:
`scripts\build_mmSolver_windows64_maya2018.bat`
2. Then run the unit tests:
`"C:\Program Files\Autodesk\maya2018\bin\mayapy.exe" tests\runTests.py > tests.log`

- mmSolver version: 
mmSolver/v0.2.2 (commit 0fbeb357b089fd6f2c2914b0eed22d0967403996)

- Maya version:
```
Operating System: Microsoft Windows 8 Business Edition, 64-bit  (Build 9200)

Cut ID: 201606150345-997974
Maya Version: Autodesk Maya 2017
Maya API: 201700
Qt Version: 5.6.1
Compositing Manager: True
Window Manager: Windows Aero
GPU:   Version : 2016.3.18.11. Feature Level 5.
  Adapter : NVIDIA GeForce GTX 1050
  Vendor ID: 4318. Device ID : 7309
  Driver : C:\WINDOWS\System32\DriverStore\FileRepository\k127369.inf_amd64_b8b3c10a6624488c\igdumdim64.dll,C:\WINDOWS\System32\DriverStor:23.20.16.4973.
  API : DirectX V.11.
  Max texture size : 16384 * 16384.
  Max tex coords : 32
  Shader versions supported (Vertex: 5, Geometry: 5, Pixel 5).
  Active stereo support available : 0
  GPU Memory Limit : 4096 MB.
  CPU Memory Limit: 30988.9 MB.
```

- Operating System (OS): 
```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
```
- Python version: 
Python 2.7.14
 
- C++ compiler version: 
```
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
```

**Comment by david-cattermole** [comment]
It seems this bug was fixed in commit 2953549c3200e7e89bf8312244934543fdb0a712.

The solver type hard-coded for the failing unit test was levmar which was not available during the unit test run. I have switched this to cminpack_lm and the test appears to work.

https://github.com/david-cattermole/mayaMatchMoveSolver/commit/2953549c3200e7e89bf8312244934543fdb0a712

The commit is part of the solver_issue54 branch and the #54 issue.

This is fixed and will be merged as part of issue #54.
