### ISSUE TITLE
Maya Tool - Solver UI - Right-click shelf menu does not work

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#101]
### Problem
Running a Python solve with the supplied Python functions, or using the shelf button right-click menu causes a traceback error.

**Expected behavior:**  
When right-clicking on the Solver UI button and running a solve on the current frame, I'd expect the solver to run. 

**Actual behavior:**  
1) Run command (or press shelf button right-click menu "Run Solver (Current Frame)"):
```
import mmSolver.tools.solver.tool as solver
solver.run_solve_on_all_frames()
```
A traceback is printed:
```
# Warning: mmSolver.tools.solver.tool : Could not get window. # 
# Error: run_solve_ui() takes exactly 5 arguments (4 given)
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "/home/dcatterm/maya/2017/modules/mayaMatchMoveSolver-0.2.2-maya2017-linux/python/mmSolver/tools/solver/tool.py", line 90, in run_solve_on_current_frame
#     run_solve(override_current_frame=True)
#   File "/home/dcatterm/maya/2017/modules/mayaMatchMoveSolver-0.2.2-maya2017-linux/python/mmSolver/tools/solver/tool.py", line 71, in run_solve
#     win,
# TypeError: run_solve_ui() takes exactly 5 arguments (4 given) # 
```

### Versions
- mmSolver version: 
v0.2.2

- Maya version:
Maya 2017.

- Operating System (OS): 
Linux; CentOS 6.x

- Python version: 
2.7

**Comment by david-cattermole** [comment]
This is now merged into master and deployed into release v0.2.3.
