### ISSUE TITLE
Maya Tools - Marker/Bundle Selection Toggle tool finds connection to MayaNodeEditorSavedTabsInfo

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#109]
### Problem
When toggling the markers/bundle selection the "MayaNodeEditorSavedTabsInfo" is incorrectly detected as a Marker node, and causes an error.

**Expected behavior:**  
Toggling the selection between Markers and Bundles should not error, even if a "MayaNodeEditorSavedTabsInfo" node is connected.

**Actual behavior:**  
When toggling the selection of Markers/Bundles, when a connection to a "MayaNodeEditorSavedTabsInfo" node exists, an error will be raised.

The error:
```
import mmSolver.tools.selection.tools as selection_tool;selection_tool.swap_between_selected_markers_and_bundles();
# Error: mmSolver._api.marker : Given Marker node name is invalid: name=u'MayaNodeEditorSavedTabsInfo' #
# Error: (kFailure): NULL object returned
# Traceback (most recent call last):
#   File "<maya console>", line 1, in <module>
#   File "/home/user/maya/2017/modules/mayaMatchMoveSolver-0.2.3-maya2017-linux/python/mmSolver/tools/selection/tools.py", line 37, in swap_between_selected_markers_and_bundles
#     mkr_nodes = convert_selection.get_markers_from_bundles(node_filtered['bundle'])
#   File "/home/user/maya/2017/modules/mayaMatchMoveSolver-0.2.3-maya2017-linux/python/mmSolver/tools/selection/convert.py", line 43, in get_markers_from_bundles
#     mkr_list = bnd.get_marker_list()
#   File "/home/user/maya/2017/modules/mayaMatchMoveSolver-0.2.3-maya2017-linux/python/mmSolver/_api/bundle.py", line 235, in get_marker_list
#     mkr = mmSolver._api.marker.Marker(node=conn)
#   File "/home/user/maya/2017/modules/mayaMatchMoveSolver-0.2.3-maya2017-linux/python/mmSolver/_api/marker.py", line 64, in __init__
#     raise e
# RuntimeError: (kFailure): NULL object returned # 
```

### Versions

mmSolver v0.2.3 (and probably all v0.2.x versions at least).

**Comment by david-cattermole** [comment]
We have fixed this problem by testing for exactly the node type of a Marker or Bundle when querying connections.

This is merged into the master branch, and may be back-ported to the v0.2.x if needed.
