### ISSUE TITLE
Bug - Center Two Dee errors when nothing is selected

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#117]
### Problem / Feature
The "Center Two Dee" tool errors when nothing is selected and the camera is not referenced.

**Expected behavior:**
1) Open a new scene.
2) Look though the default "persp" camera.
3) Deselect all nodes.
4) Press "Center Two Dee" tool on the mmSolver shelf.
5) A warning should be printed telling the user the camera cannot be uncentered because it's was never centered to begin with.

**Actual behavior:**
From step 5 above, we get the following error:
```
import mmSolver.tools.centertwodee.tool;
mmSolver.tools.centertwodee.tool.main();
# Warning: mmSolver.tools.centertwodee.tool : No objects selected, removing 2D centering. # 
# Error: Node 'perspShape' is not from a referenced file.
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.3.0-maya2017-win64\python\mmSolver\tools\centertwodee\tool.py", line 85, in main
#     reproject_utils.reset_pan_zoom(cam_tfm, cam_shp)
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.3.0-maya2017-win64\python\mmSolver\utils\reproject.py", line 167, in reset_pan_zoom
#     node_utils.set_attr(plug, value, relock=True)
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.3.0-maya2017-win64\python\mmSolver\utils\node.py", line 64, in set_attr
#     is_referenced = node_is_referenced(node)
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.3.0-maya2017-win64\python\mmSolver\utils\node.py", line 47, in node_is_referenced
#     return maya.cmds.referenceQuery(node, referenceNode=True)
# RuntimeError: Node 'perspShape' is not from a referenced file. # 
```

### Software Versions
This error happens on the commit 25c353e2b99bc3a86144ea1790ed06589df7e8b4 (beta 0.3.0), but may happen on other versions too.

**Comment by david-cattermole** [comment]
This is fixed and pushed to the master branch.
