### ISSUE TITLE
Maya Tool - Convert to Marker errors with multiple nodes selected

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#132]
### Problem
The [Convert to Marker](https://david-cattermole.github.io/mayaMatchMoveSolver/tools_createnode.html#convert-to-marker) errors when multiple nodes are selected and the tool is run.

**Expected behavior:**
The tool should be able to convert multiple 3D transforms to Markers, with one run of the tool.

**Actual behavior:**
A bug exists that stops the tool after the first node has been converted.

### Steps to Reproduce

1. Select 2 animated 3D transforms.
2. Activate a 3D viewport with a perspective camera (but not camera "persp")
3. Run "Convert to Marker" tool.

Error:
```
# Error: line 1: 'perspShape2.pan' already has an incoming connection from 'mmReprojection1.outPan'.
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:\Users\user\Documents\maya\2016\modules\mayaMatchMoveSolver-0.3.1-maya2016-win64\python\mmSolver\tools\convertmarker\tool.py", line 79, in main
#     end_frame,
#   File "C:\Users\user\Documents\maya\2016\modules\mayaMatchMoveSolver-0.3.1-maya2016-win64\python\mmSolver\tools\convertmarker\lib.py", line 40, in convert_nodes_to_marker_data_list
#     reproj = reproject_utils.create_reprojection_on_camera(cam_tfm, cam_shp)
#   File "C:\Users\user\Documents\maya\2016\modules\mayaMatchMoveSolver-0.3.1-maya2016-win64\python\mmSolver\utils\reproject.py", line 100, in create_reprojection_on_camera
#     maya.cmds.connectAttr(node + '.outPan', cam_shp + '.pan')
# RuntimeError: 'perspShape2.pan' already has an incoming connection from 'mmReprojection1.outPan'. # 

```

### Software Versions
- mmSolver version: v0.3.1 (perhaps versions before that too)

- Maya version: All supported Maya versions.
- Operating System (OS): Windows and Linux.

**Comment by david-cattermole** [comment]
This bug is now fixed and merged into the develop branch. 

It will be released in v0.3.2.
