### ISSUE TITLE
Maya Tool - Convert Markers tool fails to run in v0.3.2

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#134]
### Problem
Running the Convert Markers tool in mmSolver v0.3.2 errors due to a typo in the module names.
### Steps to Reproduce

``` python
import mmSolver.tools.convertmarker.tool;
mmSolver.tools.convertmarker.tool.main();
# Error: global name 'markergroup' is not defined
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "/home/user/maya/modules/mayaMatchMoveSolver-0.3.2-maya2018-linux/python/mmSolver/tools/convertmarker/tool.py", line 91, in main
#     mkr_grp = markergroup.MarkerGroup().create_node(cam=cam)
# NameError: global name 'markergroup' is not defined # 
```

### Software Versions
- mmSolver version: v0.3.2

- Maya version: All Maya versions.

- Operating System (OS): All supported operating systems.

**Comment by david-cattermole** [comment]
This is now fixed in the `develop` and `master` branches and will be released as soon as possible with the v0.3.3 release.
