### ISSUE TITLE
Maya Tool - Create Controller - World Space Controller with parent nodes fails to "Remove Controller"

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#221]
### Problem
When I try to remove a world space controller locator, it errors, but only when the world-space controller locator is a child of another transform node.

@bpatchasaheb has already created a PR for this issue: #220 

**Expected behavior:**
No error occurs.

**Actual behavior:**
The following error occurs:
```
# Error: No object matches name: group1.mmsolver_cc_identifier
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "/home/user/maya/2018/modules/mayaMatchMoveSolver-0.3.13-maya2018-linux/python/mmSolver/tools/removecontroller2/tool.py", line 43, in main
#     lib.remove_controller(selection[0], start_frame, end_frame)
#   File "/home/user/maya/2018/modules/mayaMatchMoveSolver-0.3.13-maya2018-linux/python/mmSolver/tools/createcontroller2/lib.py", line 450, in remove_controller
#     parent_node_attr_value = cmds.getAttr(parent_node+"."+ATTRIBUTE_IDENTIFIER_NAME)
# ValueError: No object matches name: group1.mmsolver_cc_identifier #
```

### Steps to Reproduce

1. Select (referenced) rig controller.
2. Create world space controller locator using the GUI; "mmSolver > General Tools > Create Controller..."
3. Group the world-space controller locator, and move the group.
4. Select the world-space controller locator.
5. Remove controller; "mmSolver > General Tools > Remove Controller"
6. Error (see above).

### Software Versions

- mmSolver version: v0.3.13
- Maya version: All supported
- Operating System (OS): All supported

**Comment by david-cattermole** [comment]
The PR #220 from @bpatchasaheb appears to fix the problem, and has been merged.

This will be included in the next release of mmSolver; v0.3.14.
