### ISSUE TITLE
Solver - Error Creating Marker Deviation AnimCurves

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#224]
### Problem
Sometimes an error is returned after solving. The reproduction steps are unknown, but the traceback is helpful.

**Expected behavior:**
No error should occur.

**Actual behavior:**
Script Editor error:
```
ERROR: [maya] in method 'MDoubleArray_append', argument 2 of type 'double'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/tools/solver/tool.py", line 127, in run_solve
#     win,
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/tools/solver/lib/collection.py", line 811, in run_solve_ui
#     info_fn=info_fn,
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/tools/solver/lib/collection.py", line 672, in execute_collection
#     mmapi.update_deviation_on_markers(mkr_list, solres_list)
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/_api/marker.py", line 1324, in update_deviation_on_markers
#     mkr.set_deviation(frm_list, dev_list)
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/_api/marker.py", line 869, in set_deviation
#     anim_type=OpenMayaAnim.MFnAnimCurve.kAnimCurveTU)
#   File "/homes/user/maya/2018/modules/mayaMatchMoveSolver-0.3.12-maya2018-linux/python/mmSolver/utils/animcurve.py", line 103, in create_anim_curve_node_apione
#     value_array.append(value)
# TypeError: in method 'MDoubleArray_append', argument 2 of type 'double'
```

### Steps to Reproduce

The steps to reproduce the problem are unknown.

### Software Versions

- mmSolver version: v0.3.12+
- Maya version: Maya 2018 (and probably others)
- Operating System (OS): Reported on Linux (but may happen on Windows too)

**Comment by david-cattermole** [comment]
A fix has been added to the `develop_v0.3.x` branch, it will be released in v0.3.14.
