### ISSUE TITLE
Maya Tool - Unlinking a Bundle from a Marker errors

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#241]
### Problem
When trying to unlink a Marker and Bundle link, an error is raised.

**Expected behavior:**
No error should occur.

**Actual behavior:**
An error occurs:
```
# Error: 'NoneType' object has no attribute 'get_node'
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:\Users\user\Documents\maya\2022\modules\mayaMatchMoveSolver-0.4.0.alpha4-maya2022-win64\python\mmSolver\tools\linkmarkerbundle\tool.py", line 70, in unlink_marker_bundle
#     mkr.set_bundle(None)
#   File "C:\Users\user\Documents\maya\2022\modules\mayaMatchMoveSolver-0.4.0.alpha4-maya2022-win64\python\mmSolver\_api\marker.py", line 1015, in set_bundle
#     self._unlink_from_bundle()
#   File "C:\Users\user\Documents\maya\2022\modules\mayaMatchMoveSolver-0.4.0.alpha4-maya2022-win64\python\mmSolver\_api\marker.py", line 1072, in _unlink_from_bundle
#     bnd_node = bnd.get_node()
# AttributeError: 'NoneType' object has no attribute 'get_node' # 
```

### Steps to Reproduce

The exact steps are unknown, but try the following...

1. Select a Marker
2. Run "unlink" tool, once or more times.

1. Select a Bundle
1. Run "unlink" tool, once or more times.

### Software Versions

- mmSolver version: v0.4.0.alpha4
- Maya version: Maya 2022
- Operating System (OS): Windows

**Comment by david-cattermole** [comment]
This is now fixed and will be released in v0.4.0 and v0.4.0-alpha6.
