### ISSUE TITLE
Maya Tool - Solver UI - Removing Collection Does Not Change Active Collection or Update UI

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#50]
If you have 2 collections, A and B, then delete B.
The UI does not update, and does not correctly switch to A.

Closing the UI and re-opening it does not select an active collection, and therefore fails to update the UI.

This also causes the following traceback error (sometimes):
```
# Traceback (most recent call last):
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\ui\uimodels.py", line 420, in data
#     value = get_attr_func()
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\ui\solver_nodes.py", line 184, in attrs
#     n = self.stepNode()
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\ui\solver_nodes.py", line 112, in stepNode
#     n = lib_collection.get_named_solver_step_from_collection(col, name)
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\lib\collection.py", line 296, in get_named_solver_step_from_collection
#     step_list = get_solver_steps_from_collection(col)
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\lib\collection.py", line 289, in get_solver_steps_from_collection
#     ensure_solver_steps_attr_exists(col)
#   File "C:\Users\catte\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\lib\collection.py", line 264, in ensure_solver_steps_attr_exists
#     attrs = maya.cmds.listAttr(node)
# ValueError: No object matches name: collection2
```

This is using Maya 2019.

**Comment by david-cattermole** [comment]
This has been fixed in commit. 4ae01a88dd8c3ce7efc573255f039c6add1fbaf6
