### ISSUE TITLE
Core Solver - Returned Error Values can be NaN

### ISSUE THREAD

**Issue by david-cattermole** [david-cattermole/mayaMatchMoveSolver#51]
Solving with CMinpack in the latest release can cause the following traceback, if the error values are NaN.

```
# Traceback (most recent call last):
#   File "C:\Users\Anil Reddy\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\ui\solver_window.py", line 421, in apply
#     lib_collection.run_solve_ui(col, refresh_state, log_level, self)
#   File "C:\Users\Anil Reddy\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\lib\collection.py", line 511, in run_solve_ui
#     status_fn=status_fn,
#   File "C:\Users\Anil Reddy\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\tools\solver\lib\collection.py", line 445, in execute_collection
#     status_fn=status_fn,
#   File "C:\Users\Anil Reddy\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\_api\collection.py", line 816, in execute
#     solres = solveresult.SolveResult(solve_data)
#   File "C:\Users\Anil Reddy\Documents\maya\2019\modules\mayaMatchMoveSolver-0.2.0-maya2019-win64\python\mmSolver\_api\solveresult.py", line 97, in _init_
#     self._error_stats[name] = typ(value[0])
# ValueError: invalid literal for float(): -nan(ind)
```

**Comment by david-cattermole** [comment]
Use the files "mmSolverBasicSolve_afterSolve_v002.ma" and "mmSolverBasicSolve_beforeSolve_v002.ma" to test this bug.

**Comment by david-cattermole** [comment]
Using the latest development version, it seems "max_frame_error" is now acting up (perhaps because it has a 0.0 error?).

```
// mmSolver.tools.solver.lib.collection : Average Error: 0.00 pixels // 
# Traceback (most recent call last):
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.2.0-maya2017-win64\python\mmSolver\tools\solver\ui\solver_window.py", line 421, in apply
#     lib_collection.run_solve_ui(col, refresh_state, log_level, self)
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.2.0-maya2017-win64\python\mmSolver\tools\solver\lib\collection.py", line 513, in run_solve_ui
#     status_fn=status_fn,
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.2.0-maya2017-win64\python\mmSolver\tools\solver\lib\collection.py", line 453, in execute_collection
#     log_solve_results(log, solres_list, total_time=e-s)
#   File "C:\Users\catte\Documents\maya\2017\modules\mayaMatchMoveSolver-0.2.0-maya2017-win64\python\mmSolver\tools\solver\lib\collection.py", line 171, in log_solve_results
#     int(max_frame_error[0])
# TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Comment by david-cattermole** [comment]
This is now fixed, unless proven otherwise.
